#!/usr/bin/python
#
# build the target filesystem
#

import os

Import('env')

target = env['TARG']
cross = env['CROSS']

pwd = os.getcwd()

if target == 'mvp':
    dongle = env.Command('../dongle.bin.mvpmc', 0,
                         'cd ' + pwd + ' && CROSS=' + cross + ' ./dongle.sh')
    env.Depends(dongle, 'dongle.sh')
elif target == 'nmt':
    dongle = env.Command('../nmtfs.tar.gz', 0,
                         'cd ' + pwd + ' && CROSS=' + cross + ' ./nmt.sh')
    env.Depends(dongle, 'nmt.sh')
elif target == 'mvphd':
    dongle = env.Command('../mvphd.tar.gz', 0,
                         'cd ' + pwd + ' && CROSS=' + cross + ' ./mvphd.sh')
    env.Depends(dongle, 'mvphd.sh')

Return('dongle')
