#!/usr/bin/python
#
# Build a cross-compiler for the current target
#

import os

Import('env')

home = os.environ['HOME']
downloads = env['DOWNLOADS']
target = env['TARG']
pwd = os.getcwd()

if target == 'mvp':
    file = downloads + '/buildroot-20060710.tar.bz2'
    url = 'http://www.mvpmc.org/dl/buildroot-20060710.tar.bz2'
    uclibc = os.system(pwd +'/mvpmc-uclibc.sh '+file + ' ' + url)
elif target == 'nmt':
    uclibc = os.system(pwd +'/mvpmc-nmt.sh ' + downloads)

Return('uclibc')
