#!/usr/bin/python
#
# libosd
#

Import ('env')

dir = env['BUILD_DIR']
target = env['TARG']
libdir = env['INSTLIBDIR']
freetype = env['INSTINCDIR'] + '/freetype2'
bindir = env['INSTBINDIR']

src = [ 'cursor.c', 'font.c', 'gfx.c', 'init.c', 'fb.c', 'osd.c' ]

static = env.StaticLibrary('osd', src,
                        CPPPATH = [ env['INCDIR'], env['INSTINCDIR'],
				  freetype, '.' ])
shared = env.SharedLibrary('osd', src,
                        CPPPATH = [ env['INCDIR'], env['INSTINCDIR'],
				  freetype, '.' ])

inst = env.Install(libdir, [ static, shared ])

if target == 'mvp':
	osdtest = env.Program('osdtest',
	      	              [ 'osdtest.c' ],
	                      CPPPATH = [ env['INCDIR'], env['INSTINCDIR'] ],
	                      LIBS = [ 'osd', 'dl' ],
	                      LIBPATH = [ libdir ],
	                      LINKFLAGS = [ ])
	inst2 = env.Install(bindir, osdtest)
	env.Depends(osdtest, static)

Return('inst')
