#!/usr/bin/python
#

Import('env')

target = env['TARG']
dir = env['BUILD_DIR']

osd = env.SConscript('libosd/SConscript',
		     build_dir='libosd/'+dir, duplicate=0)
input = env.SConscript('libinput/SConscript',
		       build_dir='libinput/'+dir, duplicate=0)
gw = env.SConscript('libgw/SConscript',
		    build_dir='libgw/'+dir, duplicate=0)
refmem = env.SConscript('librefmem/SConscript',
			build_dir='librefmem/'+dir, duplicate=0)
av = env.SConscript('libav/SConscript',
		    build_dir='libav/'+dir, duplicate=0)

libs = [ osd, input, gw, refmem, av ]

Return('libs')
