#!/usr/bin/python
#
# build third-party libraries
#

import os

Import('env')

target = env['TARG']

microhttpd = env.SConscript('microhttpd/SConscript')
curl = env.SConscript('curl/SConscript')
#zlib = env.SConscript('zlib/SConscript')
#png = env.SConscript('libpng/SConscript')
#jpg = env.SConscript('jpeg/SConscript')
#mw = env.SConscript('microwindows/SConscript')
#a52 = env.SConscript('a52dec/SConscript')
#expat = env.SConscript('expat/SConscript')
#dvb = env.SConscript('libdvbpsi/SConscript')
#id3 = env.SConscript('libid3/SConscript')
#tremor = env.SConscript('Tremor/SConscript')
#ncurses = env.SConscript('ncurses/SConscript')
#mysql = env.SConscript('mysql/SConscript')

common = [ microhttpd, curl ]

if target == 'nmt':
    directfb = env.SConscript('directfb/SConscript')

if target != 'host':
    freetype = env.SConscript('freetype/SConscript')

#libs = [ zlib, png, jpg, mw, a52, expat, dvb, id3, tremor, ncurses, mysql ]

#if target == 'mvp':
#	flac = env.SConscript('flac/SConscript')
#	libs.append(flac)

if target == 'nmt':
    libs = common + [ freetype, directfb ]
elif target == 'mvp':
    libs = common + [ freetype ]
elif target == 'host':
    libs = common
elif target == 'mg35':
    libs = common + [ freetype ]
elif target == 'mvphd':
    libs = common + [ freetype ]

Return('libs')
