#!/usr/bin/python
#
# build third-party libraries
#

import os

Import('env')

target = env['TARG']

freetype = env.SConscript('freetype/SConscript')
microhttpd = env.SConscript('microhttpd/SConscript')
#zlib = env.SConscript('zlib/SConscript')
#png = env.SConscript('libpng/SConscript')
#jpg = env.SConscript('jpeg/SConscript')
#mw = env.SConscript('microwindows/SConscript')
#a52 = env.SConscript('a52dec/SConscript')
#expat = env.SConscript('expat/SConscript')
#dvb = env.SConscript('libdvbpsi/SConscript')
#id3 = env.SConscript('libid3/SConscript')
#tremor = env.SConscript('Tremor/SConscript')
#ncurses = env.SConscript('ncurses/SConscript')
#mysql = env.SConscript('mysql/SConscript')

if target == 'nmt':
    directfb = env.SConscript('directfb/SConscript')

#libs = [ zlib, png, jpg, mw, a52, expat, dvb, id3, tremor, ncurses, mysql ]

#if target == 'mvp':
#	flac = env.SConscript('flac/SConscript')
#	libs.append(flac)

if target == 'nmt':
    libs = [ freetype, microhttpd, directfb ]
else:
    libs = [ freetype, microhttpd ]

Return('libs')
