#!/usr/bin/python
#
# libpthread_nommu
#

Import ('env')

dir = env['BUILD_DIR']
target = env['TARG']
libdir = env['INSTLIBDIR']
bindir = env['INSTBINDIR']

src = [ 'pt.c' ]

static = env.StaticLibrary('pthread_nommu', src, CPPPATH = [ env['INCDIR'], '.' ])

inst = env.Install(libdir, [ static ])

Return('inst')
