#!/usr/bin/python
#
# SConscript
#

import os

Import ('env')

mvp = env.Copy()
target = mvp['TARG']
toplevel = mvp['TOPLEVEL']

incdir = toplevel + '/dongle/install/' + target + '/include'

headers = [ 'cmyth.h', 'mvp_av.h', 'mvp_demux.h', 'mvp_osd.h', 'mvp_widget.h',
            'mvp_refmem.h', 'mvp_debug.h', 'mvp_atomic.h', 'rfbproto.h',
            'plugin.h', 'piutil.h', 'input.h', 'gw.h',
            'vncviewer.h', 'tiwlan.h' ]

inst = env.Install(incdir, headers)

inc = env.SConscript('plugin/SConscript')

ret = [ inst, inc ]

Return('ret')
