#!/usr/bin/python
#
# build busybox
#

import os
import mvpmc

Import('env')

build_target = env['TARG']
topdir = env['TOPDIR']
bindir = '%s/dongle/install/%s/bin/' % (topdir,build_target)
instdir = '%s/dongle/install/%s/' % (topdir,build_target)

e = Environment()

if build_target == 'mvp':
    url = [ 'http://www.mvpmc.org/dl/busybox-1.1.3.tar.bz2',
            'http://busybox.net/downloads/busybox-1.1.3.tar.bz2' ]
if build_target == 'nmt':
    url = [ 'http://www.mvpmc.org/dl/busybox-1.10.0.tar.bz2',
            'http://busybox.net/downloads/busybox-1.10.0.tar.bz2' ]

target = [ bindir + 'busybox' ]

if build_target == 'mvp':
    patches = [ 'patches/busybox_config.patch',
                'patches/busybox-1.1.3.patch' ]
    cmd = [ 'make oldconfig',
            'make install' ]
if build_target == 'nmt':
    cmd = [ 'cp ../../patches/busybox_config.nmt .config',
            'make oldconfig',
            'make install',
            'cp -a _install/* %s' % instdir ]
    patches = []

build = mvpmc.OSSBuild(target, url, env, e, cmd, patches)

if build_target == 'nmt':
    env.Depends(build, 'patches/busybox_config.nmt')

Return('build')
