#!/usr/bin/python
#
# libcmyth
#

Import ('env')

dir = env['BUILD_DIR']
target = env['TARG']
libdir = env['INSTLIBDIR']
toplevel = env['TOPLEVEL']
linkmode = env['LINKMODE']

mysqldir =  toplevel + '/dongle/install/' + target + '/lib/mysql'
incdir =  toplevel + '/dongle/install/' + target + '/include'

base = [ 'bookmark.c', 'connection.c', 'debug.c', 'event.c',
         'file.c', 'freespace.c', 'keyframe.c',
         'posmap.c', 'proginfo.c', 'proglist.c', 'rec_num.c', 
         'recorder.c', 'ringbuf.c', 'socket.c', 'timestamp.c',
         'livetv.c' ]

extra = [ 'mysql_query.c', 'commbreak.c', 'mythtv_mysql.c', 'tvguide.c' ]

src = base

extraflags = "-DCMYTH_SQL"
baseflags = ""
flags = baseflags

static = env.StaticLibrary('cmyth',
                           src,
                           CPPPATH = [ env['INCDIR'], incdir, '.' ],
                           CCFLAGS=flags)

if linkmode == 'shared':
    shared = env.SharedLibrary('cmyth',
                               src,
                               CPPPATH = [ env['INCDIR'], incdir, '.' ],
                               CCFLAGS=flags)
    inst = env.Install(libdir, [ static, shared ])
else:
    inst = env.Install(libdir, [ static ])

Return('inst')
