#!/usr/bin/python
#
# build freetype
#

import os
import mvpmc

Import('env')

build_target = env['TARG']
topdir = env['TOPDIR']
libdir = '%s/dongle/install/%s/lib/' % (topdir,build_target)
incdir = '%s/dongle/install/%s/include/' % (topdir,build_target)
prefix = '%s/dongle/install/%s' % (topdir,build_target)

if build_target == 'mvp':
  cross = env['CROSS']
  config = '--host=powerpc-linux'
elif build_target == 'mg35':
  cross = env['CROSS']
  config = '--host=arm-linux --disable-shared'
elif build_target == 'nmt':
  cross = env['CROSS']
  config = '--host=mips-linux'

url = [ 'http://www.mvpmc.org/dl/freetype-2.2.1.tar.gz' ]

e = Environment()

target = [ libdir + 'libfreetype.a',
           incdir + 'ft2build.h' ]
cmd = [ './configure --prefix=%s %s' % (prefix,config),
	'cp ../../modules.cfg .',
        'make -i',
        'make -i install',
        'cp include/ft2build.h %s' % prefix ]

build = mvpmc.OSSBuild(target, url, env, e, cmd)

Return('build')
