#!/usr/bin/python
#
# build freetype
#

import os

Import('env')

home = os.environ['HOME']
cc = env['CC']
downloads = env['DOWNLOADS']
target = env['TARG']

if target == 'mvp':
  cross = '-c ' + env['CROSS']
  host = '-C --host=powerpc-linux'
elif target == 'mg35':
  cross = '-c ' + env['CROSS']
  host = '-C --host=arm-linux'
else:
  cross = ''
  host = ''

file = downloads + '/freetype-2.2.1.tar.gz'

e = Environment()
e.Tool('WGet', toolpath=['../../../scons'])

def GetSourceFile(url, output_dir, env):
  '''
  Create a node for a file retrieved via wget.
  This node can be used as a dependency in other rules.
  '''
  # Nab everything after the last slash as the filename
  basefilename = str(url)[str( url).rfind(os.sep) + 1:]
  munged = output_dir + os.sep + basefilename + os.sep + url
  node = env.SourceCode( munged, env.WGet() )
  return node

url = 'http://www.mvpmc.org/dl/freetype-2.2.1.tar.gz'
pwd = os.getcwd()

build = env.Command('../../install/' + target + '/lib/libfreetype.a', 0,
                    'scons/build_lib.sh -d ' + pwd + '/' + target +
                    '/freetype-2.2.1 -i ' + file + ' ' +
                    cross + ' ' +
                    '-I ' + pwd + '/../../install/' + target + ' ' +
                    host)

if not os.path.exists(file):
	dl = GetSourceFile(url, '#' + downloads, e)
	env.Depends(build, dl)

env.SideEffect(['../../install/' + target + '/include/freetype2/freetype/freetype.h'],
                build)
env.SideEffect(['../../install/' + target + '/include/ft2build.h'],
                build)

Return('build')
