#!/usr/bin/python
#
# Third-Party Applications
#

import os

Import('env')

target = env['TARG']

apps = []

if target == 'nmt':
    smart = env.SConscript(['smartmontools/SConscript'])
    apps = [ smart ]

if target == 'nmt' or target == 'mvp':
    busybox = env.SConscript(['busybox/SConscript'])
    strace = env.SConscript(['strace/SConscript'])
    dropbear = env.SConscript(['dropbear/SConscript'])
    apps = apps + [ busybox, strace, dropbear ]

if target == 'mvp':
    ntp = env.SConscript(['ntpclient/SConscript'])
    mtd = env.SConscript(['mtd/SConscript'])
    fuse = env.SConscript([ 'fuse/SConscript'])
    djmount = env.SConscript('djmount/SConscript')
    nbtscan = env.SConscript('nbtscan/SConscript')
    env.Depends(djmount, fuse)
    apps = apps + [ ntp, mtd, fuse, djmount, nbtscan ]

Return('apps')
