#!/usr/bin/python

import os

Import('env')

busybox = env.SConscript(['busybox/SConscript'])
ntp = env.SConscript(['ntpclient/SConscript'])
dropbear = env.SConscript(['dropbear/SConscript'])
mtd = env.SConscript(['mtd/SConscript'])
fuse = env.SConscript([ 'fuse/SConscript'])
djmount = env.SConscript('djmount/SConscript')
nbtscan = env.SConscript('nbtscan/SConscript')

apps = [ busybox, ntp, dropbear, mtd, fuse, djmount, nbtscan ]

Return('apps')

